# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "MicroMDM"
license = "MIT"
licenselink = "https://github.com/micromdm/website/blob/master/LICENSE.md"
description = ""
homepage = "https://micromdm.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
